<?xml version="1.0" encoding="utf-8"?><Database Name="QLXM" Class="QLXMDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-IQDI89M;Initial Catalog=QLXM;User ID=sa" SettingsObjectName="NET_DoAn.Properties.Settings" SettingsPropertyName="QLXMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="Usename" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Xe" Member="Xes">
    <Type Name="Xe">
      <Column Name="MaXe" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenXe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Maloaixe" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GiaNhap" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SoKhung" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoMay" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mau" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Dungtich" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TinhTrang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Xe_BaoHanh" Member="BaoHanhs" ThisKey="MaXe" OtherKey="MaXe" Type="BaoHanh" />
      <Association Name="Xe_ChitietHDN" Member="ChitietHDNs" ThisKey="MaXe" OtherKey="MaXe" Type="ChitietHDN" />
      <Association Name="Xe_ChitietHDX" Member="ChitietHDXes" ThisKey="MaXe" OtherKey="MaXe" Type="ChitietHDX" />
      <Association Name="Loaixe_Xe" Member="Loaixe" ThisKey="Maloaixe" OtherKey="Maloaixe" Type="Loaixe" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NCC_Xe" Member="NCC" ThisKey="MaNCC" OtherKey="MaNCC" Type="NCC" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.BaoHanh" Member="BaoHanhs">
    <Type Name="BaoHanh">
      <Column Name="MaPhieuBH" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaXe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TGBH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayMua" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Xe_BaoHanh" Member="Xe" ThisKey="MaXe" OtherKey="MaXe" Type="Xe" IsForeignKey="true" />
      <Association Name="KhachHang_BaoHanh" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_BaoHanh" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChitietHDN" Member="ChitietHDNs">
    <Type Name="ChitietHDN">
      <Column Name="MaHDN" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaXe" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Dongia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Soluong" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ThueVAT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Xe_ChitietHDN" Member="Xe" ThisKey="MaXe" OtherKey="MaXe" Type="Xe" IsForeignKey="true" />
      <Association Name="HoaDonNhap_ChitietHDN" Member="HoaDonNhap" ThisKey="MaHDN" OtherKey="MaHDN" Type="HoaDonNhap" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ChitietHDX" Member="ChitietHDXes">
    <Type Name="ChitietHDX">
      <Column Name="MaHDX" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaXe" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Dongia" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Soluong" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ThueVAT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Xe_ChitietHDX" Member="Xe" ThisKey="MaXe" OtherKey="MaXe" Type="Xe" IsForeignKey="true" />
      <Association Name="HoaDonXuat_ChitietHDX" Member="HoaDonXuat" ThisKey="MaHDX" OtherKey="MaHDX" Type="HoaDonXuat" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonNhap" Member="HoaDonNhaps">
    <Type Name="HoaDonNhap">
      <Column Name="MaHDN" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="HoaDonNhap_ChitietHDN" Member="ChitietHDNs" ThisKey="MaHDN" OtherKey="MaHDN" Type="ChitietHDN" />
      <Association Name="NCC_HoaDonNhap" Member="NCC" ThisKey="MaNCC" OtherKey="MaNCC" Type="NCC" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDonXuat" Member="HoaDonXuats">
    <Type Name="HoaDonXuat">
      <Column Name="MaHDX" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayXuat" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="HoaDonXuat_ChitietHDX" Member="ChitietHDXes" ThisKey="MaHDX" OtherKey="MaHDX" Type="ChitietHDX" />
      <Association Name="KhachHang_HoaDonXuat" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
      <Association Name="NhanVien_HoaDonXuat" Member="NhanVien" ThisKey="MaNV" OtherKey="MaNV" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenKH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ghichu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="KhachHang_BaoHanh" Member="BaoHanhs" ThisKey="MaKH" OtherKey="MaKH" Type="BaoHanh" />
      <Association Name="KhachHang_HoaDonXuat" Member="HoaDonXuats" ThisKey="MaKH" OtherKey="MaKH" Type="HoaDonXuat" />
    </Type>
  </Table>
  <Table Name="dbo.Loaixe" Member="Loaixes">
    <Type Name="Loaixe">
      <Column Name="Maloaixe" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Tenloaixe" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Loaixe_Xe" Member="Xes" ThisKey="Maloaixe" OtherKey="Maloaixe" Type="Xe" />
    </Type>
  </Table>
  <Table Name="dbo.NCC" Member="NCCs">
    <Type Name="NCC">
      <Column Name="MaNCC" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNCC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NCC_Xe" Member="Xes" ThisKey="MaNCC" OtherKey="MaNCC" Type="Xe" />
      <Association Name="NCC_HoaDonNhap" Member="HoaDonNhaps" ThisKey="MaNCC" OtherKey="MaNCC" Type="HoaDonNhap" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNV" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngaysinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Diachi" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CMND" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ngayvaolam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NhanVien_BaoHanh" Member="BaoHanhs" ThisKey="MaNV" OtherKey="MaNV" Type="BaoHanh" />
      <Association Name="NhanVien_HoaDonXuat" Member="HoaDonXuats" ThisKey="MaNV" OtherKey="MaNV" Type="HoaDonXuat" />
    </Type>
  </Table>
</Database>